### ISSUE TITLE
[BUG] Honeypot ID not regenerated

### ISSUE THREAD

**Issue by jevgen** [Highfivery/wordpress-zero-spam#295]
**Describe the bug**
When pressed button "Regenerate Honeypot ID" in settings, it is not regenerated. 

**To Reproduce**
1. Go to plugin settings
2. Click on Regenerate honeypot ID
3. ID stays the same 

**Expected behavior**
Expected honeypot ID be the new. 

**Additional context**
nginx 
No errors reported in log.

**Comment by ianpegg** [comment]
Can confirm the bug can be reproduced on LiteSpeed installs too. All installs I maintain are running Zero Spam 5.2.8 and WP 5.8.2.

**Comment by bmarshall511** [comment]
@jevgen @ianpegg Thanks for letting me know. I've found the issue & will be fixed in the next release.
