### ISSUE TITLE
[FEATURE] Custom form integration

### ISSUE THREAD

**Issue by jankocian** [Highfivery/wordpress-zero-spam#297]
Hey, how do I use WP Zero Spam with a custom form?

You claim that it "can be easily integrated into any existing theme or plugin" but I could not find any example :)

I recently inherited a website that used version 3 of this plugin. The form just had a class of zerospam and `zerospam_is_valid()` method was called on form submission. How do I replicate that behavior?

Thanks a lot,
Jan

**Comment by bmarshall511** [comment]
@jankocian You can find examples under the modules directory on how to hook into zero spam validation. Let me know if you need help.
