### ISSUE TITLE
Adding API key to Google API integration has no effect [BUG]

### ISSUE THREAD

**Issue by ianpegg** [Highfivery/wordpress-zero-spam#304]
**Describe the bug**
Adding an API key to the Google Maps integration has no effect. On the plugin dashboard there is no geolocation data under 'Detections'. In the log, there is no geolocation data in the 'Country' or 'Region' columns. 

No error message appears after adding the API key and there is no error log trace reporting any kind of API issue. On the Google Cloud Platform dashboard, there are no API requests (errors or otherwise) recorded under Google Maps Embed API. Other APIs integrated with my client's site such as Maps Static and Places continue to work as normal.

**To Reproduce**
1. Go to Zero Spam settings
2. Expand the Google Maps Integration accordion
3. Click the link and follow the instructions to create a Google Maps Embed API key
4. Return to Zero Spam settings and paste the API key in
5. Hit 'Save settings'
6. Visit the Zero Spam dashboard after several days to confirm that no geolocation data is being presented in the reports

**Expected behavior**
I expected to see a map of IPs by location on the Zero Spam dashboard and geolocation data in at least one of the 'Country' or 'Region' columns under the 'Logs' tab.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6 (18G9323)
 - Browser: Chrome 
 - Version: 97.0.4692.99 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
I am running the latest release WPZS (5.2.10) and WP 5.9.

**Comment by bmarshall511** [comment]
@ianpegg Geolocation isn't provided by Google, that's used only to display the map. To enable geolocation, you'll need to use one of the geolocation services like IPstack or IPinfo.

**Comment by ianpegg** [comment]
Thanks, @bmarshall511 - I suspected I'd missed something.

Quick feedback: there is an opportunity to improve the in-plugin documentation. IPstack, IPinfo and Google Maps are all presented as 'Geolocation' settings. Any reasonable person might be forgiven for thinking that they all therefore perform the same function, whereas in fact, the first two are interchangeable, but the last one is not. 

Since entering a Maps API on its own is essentially pointless, you could also guide users to finding the resolution to the problem by displaying an error message when somebody saves a Maps API key but hasn't entered either an IPstack or IPinfo API key.

Hope this helps!
